name: Retail Sales Dashboard

on:
  workflow_dispatch:
  push:
    branches: [deployment]
  
  
  pull_request:
    branches: [deployment]

jobs:
  plan: 
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise project and view terraform plan
        run: |
          cd terraform
          terraform fmt
          terraform init
          terraform plan

  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Initialise project and view terraform plan
        run: |
          cd terraform
          terraform fmt
          terraform init
          terraform apply
